spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/volunteerAPI
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.yandex.ru
    username: eldaridiatov@yandex.ru
    password: xjjxuctwtumuvitz
    port: 465
    protocol: smpts

application:
  auth:
    jwt-secret: IldarAndLera
    jwt-expiration-time: 999999h
    cookie-name: autoTinderJWT

